Homework #4
ArsenDanilov/react-16092024 pull request #3
Opened 2024-10-11 10:55 UTC by ArsenDanilov

Разрешите, пожалуйста, пока не удалять комментарии к хукам и различным областям кода. Я к ним возвращаюсь, если что-то забываю, так легче ориентироваться. Позже я их удалю

2024-10-11 12:47 UTC, zubkov7 requested changes

2024-10-11 12:47 UTC, zubkov7 commented on src/components/ScrollBar/ScrollBar.jsx
> +    const scrollBar = document.querySelector('.scrollBar');
все перерисовки в реакте необходимо делать через изменение состояния. Поэтому для ширины необходимо сделать состояние и изменять его на скролле

2024-10-11 12:47 UTC, zubkov7 commented on src/components/ScrollBar/ScrollBar.jsx
> +  window.addEventListener("scroll", onScroll);
обработчики событий необходимо добавлять в хуке useEffect и чистить в cleanup функции

2024-10-12 07:36 UTC, ArsenDanilov commented on src/components/ScrollBar/ScrollBar.jsx
> +  window.addEventListener("scroll", onScroll);
Поправил

2024-10-12 07:37 UTC, ArsenDanilov commented on src/components/ScrollBar/ScrollBar.jsx
> +    const scrollBar = document.querySelector('.scrollBar');
Исправил, но теперь при обновлении страницы, скроллбар у меня всегда заполнен полностью. Подскажите, пожалуйста, как это исправить?

2024-10-12 15:46 UTC, zubkov7 commented on src/components/ScrollBar/ScrollBar.jsx
> +      <div className="scrollBar"></div>
нужно сюда добавить style={{ width: scrollBarWidth }}

стиль будет динамически меняться из-за изменения состояние

2024-10-12 15:46 UTC, zubkov7 commented on src/components/ScrollBar/ScrollBar.jsx
> +      const scrollBar = document.querySelector(".scrollBar");
этого делать уже не нужно будет

2024-10-13 14:39 UTC, ArsenDanilov commented on src/components/ScrollBar/ScrollBar.jsx
> +      <div className="scrollBar"></div>
Большое спасибо, поправил

2024-10-13 14:39 UTC, ArsenDanilov commented on src/components/ScrollBar/ScrollBar.jsx
> +      const scrollBar = document.querySelector(".scrollBar");
Поправил

2024-10-14 08:45 UTC, zubkov7 approved these changes

2024-10-14 13:01 UTC, merged